# Generated by Django 4.1.3 on 2022-12-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_profile_table',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
