# Generated by Django 4.1.3 on 2022-12-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0002_alter_edit_profile_table_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_profile_table',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='edit_profile_table',
            name='update_on',
        ),
    ]
