# Generated by Django 4.1.3 on 2022-12-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editprofile', '0003_remove_edit_profile_table_added_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit_profile_table',
        ),
    ]
