# Generated by Django 4.1.3 on 2023-01-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_appointment',
        ),
    ]
