# Generated by Django 4.1.3 on 2023-01-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_appointment',
            name='apointment_date',
        ),
    ]
