# Generated by Django 4.1.3 on 2022-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_alter_register_form_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_form',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='register_form',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='register_form',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
