# Generated by Django 4.1.3 on 2023-01-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_locate_city_occupation_alter_locate_city_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locate_city',
            name='occupation',
            field=models.TextField(null=True),
        ),
    ]
