# Generated by Django 4.1.3 on 2023-01-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_locate_city_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locate_city',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locate_city',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
