# Generated by Django 4.1.3 on 2023-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_locate_city_state_alter_locate_city_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='locate_city',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
