# Generated by Django 4.1.3 on 2023-01-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_locate_city_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locate_city',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='locate_city',
            name='date2',
        ),
    ]
