# Generated by Django 4.1.3 on 2022-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartPredictApp', '0002_predict_form_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict_form',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
