# Generated by Django 4.1.3 on 2022-12-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartPredictApp', '0003_alter_predict_form_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict_form',
            name='oldpeak',
            field=models.FloatField(null=True),
        ),
    ]
